name: 'Terraform with Azure backend'
description: 'Setup resources for an Azure backend'
author: 'Cor Zuurmond <jczuurmond@protonmail.com>'
inputs:
  resource_group:
    description: 'The resource group name'
    required: false
    default: 'terraform'
  storage_account:
    description: 'The storage account name'
    required: false
    default: 'tfstate'
  container_name:
    description: 'The container name'
    required: false
    default: 'tfstate'
runs:
  using: "composite"
  steps:
  - name: Create resources for Terraform Azure backend
    shell: bash
    run: |
      az group create --name ${{ inputs.resource_group }} --location westeurope
      az storage account create --resource-group ${{ inputs.resource_group }} --name ${{ inputs.storage_account }} --sku Standard_LRS --encryption-services blob
      ACCOUNT_KEY=$(az storage account keys list --resource-group ${{ inputs.resource_group }} --account-name ${{ inputs.storage_account }} -o json | jq '.[0].value' --raw-output)
      az storage container create --name ${{ inputs.container_name }} --account-name ${{ inputs.storage_account }} --account-key $ACCOUNT_KEY
